### ISSUE TITLE
{"errors":[{"code":261,"message":"Application cannot perform write actions ..... Contact Twitter"}]}

### ISSUE THREAD

**Issue by syed-ahmad** [twitterdev/twitter-webhook-boilerplate-node#7]
I've used this boilerplate app, swapped keys / tokens but I keep getting following error.

- When I provide consumer_key, consumer_secret, token and token_secret, I get following error
{"errors":[{"code":32,"message":"Could not authenticate you."}]}

- When I provide token and token_secret only, I get following error
{"errors":[{"code":261,"message":"Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com/forms/platform."}]}

Any ideas? I've raised a ticket with Twitter as well.

**Comment by andypiper** [comment]
Have you been granted access to the Account Activity API? Instructions and a link are on [this page](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview).

**Comment by andypiper** [comment]
Closing due to lack of further information.

**Comment by Tapudp** [comment]
I have been facing the same issue today on my twitter bot is it because they might have banned my bot?

**Comment by andypiper** [comment]
This is probably not the correct place to ask that question. Are you using this specific code in your bot i.e. the node webhooks application? If so, have you been granted access to the API?

If not, I'd suggest using [Twitter's help forms](https://help.twitter.com/forms), the [apps.twitter.com](https://apps.twitter.com) dashboard, and the [developer community forums](https://twittercommunity.com) to look for help.
